/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystemproject;
 

/**
 *
 * @author DELL
 */
public class Helicopter extends javax.swing.JFrame implements DefenseUnit{
   private int postion;
    /**
     * Creates new form Helicopter
     */
    public Helicopter() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Helicopter");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helicopterShootButton = new javax.swing.JButton();
        helicopterLaserButton = new javax.swing.JButton();
        helicopterMissileButton = new javax.swing.JButton();
        helicopterSoldierSpinner = new javax.swing.JSpinner();
        helicopterAmmoSpinner = new javax.swing.JSpinner();
        helicopterSlider = new javax.swing.JSlider();
        jScrollPane4 = new javax.swing.JScrollPane();
        helicopterAreaTextArea = new javax.swing.JTextArea();
        helicopterSendButton = new javax.swing.JButton();
        helicopterPositionCheckbox = new javax.swing.JCheckBox();
        helicopterAreaLbl = new javax.swing.JLabel();
        helicopterSoldierCountLbl = new javax.swing.JLabel();
        helicopterAmmoCountLbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        helicopterShootButton.setText("Shoot ");
        helicopterShootButton.setEnabled(false);
        helicopterShootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helicopterShootButtonActionPerformed(evt);
            }
        });

        helicopterLaserButton.setText("Laser Operation");
        helicopterLaserButton.setEnabled(false);

        helicopterMissileButton.setText("Missile Operation");
        helicopterMissileButton.setEnabled(false);

        helicopterSlider.setMajorTickSpacing(20);
        helicopterSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        helicopterSlider.setPaintLabels(true);
        helicopterSlider.setPaintTicks(true);
        helicopterSlider.setSnapToTicks(true);
        helicopterSlider.setValue(0);
        helicopterSlider.setInverted(true);

        helicopterAreaTextArea.setColumns(20);
        helicopterAreaTextArea.setRows(5);
        jScrollPane4.setViewportView(helicopterAreaTextArea);

        helicopterSendButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        helicopterSendButton.setText("Send");
        helicopterSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helicopterSendButtonActionPerformed(evt);
            }
        });

        helicopterPositionCheckbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        helicopterPositionCheckbox.setText("  Position");
        helicopterPositionCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helicopterPositionCheckboxActionPerformed(evt);
            }
        });

        helicopterAreaLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helicopterAreaLbl.setText("Area Not Cleared  ");

        helicopterSoldierCountLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helicopterSoldierCountLbl.setText("Soldier count");

        helicopterAmmoCountLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helicopterAmmoCountLbl.setText("Ammo count");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(helicopterLaserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helicopterPositionCheckbox)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(helicopterAreaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(helicopterShootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(helicopterMissileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(helicopterAmmoCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(helicopterAmmoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(helicopterSoldierCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(helicopterSoldierSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(helicopterSendButton)))))
                .addComponent(helicopterSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(helicopterAreaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(helicopterShootButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(helicopterMissileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(helicopterPositionCheckbox))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(helicopterLaserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helicopterSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(helicopterSoldierCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helicopterSoldierSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(helicopterAmmoCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helicopterAmmoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helicopterSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helicopterShootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helicopterShootButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helicopterShootButtonActionPerformed

    private void helicopterPositionCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helicopterPositionCheckboxActionPerformed
        // TODO add your handling code here:
        updateButtons(); 
    }//GEN-LAST:event_helicopterPositionCheckboxActionPerformed

    
    
    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
       
    }//GEN-LAST:event_btnShootActionPerformed

    private void btnSend4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        String msg = "Helicopter : " + helicopterAreaTextArea.getText();
        MainController.setDefenceMsg(msg);
    }//GEN-LAST:event_btnSendActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void helicopterSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helicopterSendButtonActionPerformed
        String msg = "Helicopter : " + jTextField1.getText();
        MainController.setDefenceMsg(msg);   
    }//GEN-LAST:event_helicopterSendButtonActionPerformed
    
         public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Helicopter().setVisible(true);
        });
    }                                  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel helicopterAmmoCountLbl;
    private javax.swing.JSpinner helicopterAmmoSpinner;
    private javax.swing.JLabel helicopterAreaLbl;
    private javax.swing.JTextArea helicopterAreaTextArea;
    private javax.swing.JButton helicopterLaserButton;
    private javax.swing.JButton helicopterMissileButton;
    private javax.swing.JCheckBox helicopterPositionCheckbox;
    private javax.swing.JButton helicopterSendButton;
    private javax.swing.JButton helicopterShootButton;
    private javax.swing.JSlider helicopterSlider;
    private javax.swing.JLabel helicopterSoldierCountLbl;
    private javax.swing.JSpinner helicopterSoldierSpinner;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

 @Override
    public void getMsgMain(String msg) {
        try{
            javax.swing.text.Document doc = helicopterAreaTextArea.getDocument();
            doc.insertString(doc.getLength(), "Maincontroller: "+ msg + "\n", null);
            helicopterAreaTextArea.setCaretPosition(doc.getLength());
            
        }catch(javax.swing.text.BadLocationException e){
        
    }
    }

@Override
    public void update(int position) {
        this.postion=position;
        updateButtons();
    }

     @Override
    public void areaClearlabel(boolean clearStatus){
        if (clearStatus){
            helicopterAreaLbl.setText("Area Cleared");
        }else {
            helicopterAreaLbl.setText("Area is Not Clear");
        }
    }

    @Override
    public void updateButtons() {
        
        if(helicopterPositionCheckbox.isSelected()){
            if(postion>60){
                helicopterMissileButton.setEnabled(true);
                helicopterLaserButton.setEnabled(true);
                helicopterShootButton.setEnabled(true);
            }else if(postion>40){
                helicopterMissileButton.setEnabled(false);
                helicopterLaserButton.setEnabled(true);
                helicopterShootButton.setEnabled(true);
            }else if(postion>20){
                helicopterMissileButton.setEnabled(false);
                helicopterLaserButton.setEnabled(false);
                helicopterShootButton.setEnabled(true);
            }else{
                helicopterMissileButton.setEnabled(false);
                helicopterLaserButton.setEnabled(false);
                helicopterShootButton.setEnabled(false);
            }
      
        }
    }

  
}








