/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystemproject;
import javax.swing.text.Position;
/**
 *
 * @author DELL
 */
public class Submarine extends javax.swing.JFrame implements DefenseUnit {
    private int position;
    /**
     * Creates new form Submarine
     */
    public Submarine() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Submarine");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subShootButton = new javax.swing.JButton();
        subMissileButton = new javax.swing.JButton();
        subSonarButton = new javax.swing.JButton();
        subMissile2Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        subTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        subTextPane = new javax.swing.JTextPane();
        subSendButton = new javax.swing.JButton();
        subSoldierSpinner = new javax.swing.JSpinner();
        subAmmoSpinner = new javax.swing.JSpinner();
        subPositionCheckbox = new javax.swing.JCheckBox();
        subEnergySlider = new javax.swing.JSlider();
        subOxygenSlider = new javax.swing.JSlider();
        subAreaLbl = new javax.swing.JLabel();
        subSoldierCountLbl = new javax.swing.JLabel();
        subAmmoCountLbl = new javax.swing.JLabel();
        subEnergyLbl = new javax.swing.JLabel();
        subOxygenLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subShootButton.setText("Shoot");
        subShootButton.setEnabled(false);

        subMissileButton.setText("Tomahawk Misile");
        subMissileButton.setEnabled(false);
        subMissileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMissileButtonActionPerformed(evt);
            }
        });

        subSonarButton.setText("Sonar Operation");
        subSonarButton.setEnabled(false);

        subMissile2Button.setText("Trident-2 Missile");
        subMissile2Button.setEnabled(false);
        subMissile2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMissile2ButtonActionPerformed(evt);
            }
        });

        subTextArea.setColumns(20);
        subTextArea.setRows(5);
        jScrollPane2.setViewportView(subTextArea);

        jScrollPane3.setViewportView(subTextPane);

        subSendButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subSendButton.setText("Send");
        subSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subSendButtonActionPerformed(evt);
            }
        });

        subPositionCheckbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subPositionCheckbox.setText("Position");
        subPositionCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subPositionCheckboxActionPerformed(evt);
            }
        });

        subEnergySlider.setMajorTickSpacing(20);
        subEnergySlider.setOrientation(javax.swing.JSlider.VERTICAL);
        subEnergySlider.setPaintLabels(true);
        subEnergySlider.setPaintTicks(true);
        subEnergySlider.setSnapToTicks(true);
        subEnergySlider.setValue(0);

        subOxygenSlider.setMajorTickSpacing(20);
        subOxygenSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        subOxygenSlider.setPaintLabels(true);
        subOxygenSlider.setPaintTicks(true);
        subOxygenSlider.setSnapToTicks(true);
        subOxygenSlider.setValue(0);

        subAreaLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subAreaLbl.setText("Area Not Cleared");

        subSoldierCountLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subSoldierCountLbl.setText("Soldier Count");

        subAmmoCountLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subAmmoCountLbl.setText("Ammo Count");

        subEnergyLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subEnergyLbl.setText("Energy");

        subOxygenLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subOxygenLbl.setText("Oxygen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(subShootButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(subSonarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subMissileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subMissile2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(subAreaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subSoldierCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subAmmoCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subSoldierSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subAmmoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subEnergyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(subSendButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(subPositionCheckbox)
                                .addGap(90, 90, 90)))
                        .addComponent(subEnergySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subOxygenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subOxygenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subAreaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subSoldierSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subSoldierCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(subAmmoSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subShootButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addComponent(subSonarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(subAmmoCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subMissileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subMissile2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subOxygenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subEnergyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subOxygenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subPositionCheckbox)
                            .addComponent(subEnergySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMissileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMissileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMissileButtonActionPerformed

    private void subPositionCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subPositionCheckboxActionPerformed

    }//GEN-LAST:event_subPositionCheckboxActionPerformed

    private void subMissile2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMissile2ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMissile2ButtonActionPerformed

    private void subSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subSendButtonActionPerformed
       String msg = "Submarine : " + subTextPane.getText();
       MainController.setDefenceMsg(msg); 
    }//GEN-LAST:event_subSendButtonActionPerformed
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Submarine().setVisible(true);
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel subAmmoCountLbl;
    private javax.swing.JSpinner subAmmoSpinner;
    private javax.swing.JLabel subAreaLbl;
    private javax.swing.JLabel subEnergyLbl;
    private javax.swing.JSlider subEnergySlider;
    private javax.swing.JButton subMissile2Button;
    private javax.swing.JButton subMissileButton;
    private javax.swing.JLabel subOxygenLbl;
    private javax.swing.JSlider subOxygenSlider;
    private javax.swing.JCheckBox subPositionCheckbox;
    private javax.swing.JButton subSendButton;
    private javax.swing.JButton subShootButton;
    private javax.swing.JLabel subSoldierCountLbl;
    private javax.swing.JSpinner subSoldierSpinner;
    private javax.swing.JButton subSonarButton;
    private javax.swing.JTextArea subTextArea;
    private javax.swing.JTextPane subTextPane;
    // End of variables declaration//GEN-END:variables

    
   
    @Override
    public void getMsgMain(String msg) {
        try{
            javax.swing.text.Document doc = subTextArea.getDocument();
            doc.insertString(doc.getLength(), "Maincontroller: "+ msg + "\n", null);
            subTextArea.setCaretPosition(doc.getLength());
            
        }catch(javax.swing.text.BadLocationException e){
        
    }
    }
     
    @Override
    public void update(int position) {
        this.position=position;
        updateButtons();
    }
    
     @Override
    public void areaClearlabel(boolean clearStatus) {
        if (clearStatus){
            subAreaLbl.setText("Area Cleared");
        }else {
            subAreaLbl.setText("Area is Not Clear");
        }
    }

   
    @Override
    public void updateButtons() {
        
        if(subPositionCheckbox.isSelected()){
          
            
            if(position>80){
                subShootButton.setEnabled(true);
                subSonarButton.setEnabled(true);
                subMissileButton.setEnabled(true);
                subMissile2Button.setEnabled(true);
            }else if(position>60){
                subShootButton.setEnabled(true);
                subSonarButton.setEnabled(true);
                subMissileButton.setEnabled(true);
                subMissile2Button.setEnabled(false);
            }else if(position>40){
                subShootButton.setEnabled(true);
                subSonarButton.setEnabled(true);
                subMissileButton.setEnabled(false);
                subMissile2Button.setEnabled(false);
            }else if(position>20){
                subShootButton.setEnabled(true);
                subSonarButton.setEnabled(false);
                subMissileButton.setEnabled(false);
                subMissile2Button.setEnabled(false);
            }else{
                subShootButton.setEnabled(false);
                subSonarButton.setEnabled(false);
                subMissileButton.setEnabled(false);
                subMissile2Button.setEnabled(false);
            }
              
           }
        }
    }
    

    
   
