/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystemproject;
//import javax.swing.text.Position;
/**
 *
 * @author DELL
 */
public final class Tank extends javax.swing.JFrame implements DefenseUnit{
     private int position;
    /**
     * Creates new form Tank
     */
    public Tank() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Tank");
        setVisible(true);
          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shootButton = new javax.swing.JButton();
        redarOperation = new javax.swing.JButton();
        missileButton = new javax.swing.JButton();
        rotateButton = new javax.swing.JButton();
        soldierSpinner = new javax.swing.JSpinner();
        ammoSpinner = new javax.swing.JSpinner();
        tankSlider = new javax.swing.JSlider();
        jScrollPane4 = new javax.swing.JScrollPane();
        tankTextArea = new javax.swing.JTextArea();
        tankSendButton = new javax.swing.JButton();
        tankPositionCheckbox = new javax.swing.JCheckBox();
        tankAreaTextArea = new javax.swing.JLabel();
        tankSoldierCountLbl = new javax.swing.JLabel();
        tankAmmoCountLbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shootButton.setText("Shoot");
        shootButton.setEnabled(false);

        redarOperation.setText("Redar Operation");
        redarOperation.setEnabled(false);
        redarOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redarOperationActionPerformed(evt);
            }
        });

        missileButton.setText("Missile Operation");
        missileButton.setEnabled(false);
        missileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missileButtonActionPerformed(evt);
            }
        });

        rotateButton.setText("Rotate shooting");
        rotateButton.setEnabled(false);
        rotateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateButtonActionPerformed(evt);
            }
        });

        tankSlider.setMajorTickSpacing(20);
        tankSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        tankSlider.setPaintLabels(true);
        tankSlider.setPaintTicks(true);
        tankSlider.setSnapToTicks(true);
        tankSlider.setValue(0);

        tankTextArea.setColumns(20);
        tankTextArea.setRows(5);
        jScrollPane4.setViewportView(tankTextArea);

        tankSendButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tankSendButton.setText("Send");
        tankSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankSendButtonActionPerformed(evt);
            }
        });

        tankPositionCheckbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tankPositionCheckbox.setText("Position");
        tankPositionCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankPositionCheckboxActionPerformed(evt);
            }
        });

        tankAreaTextArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tankAreaTextArea.setText("Area Not Cleared");

        tankSoldierCountLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tankSoldierCountLbl.setText("Soldier Count");

        tankAmmoCountLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tankAmmoCountLbl.setText("Ammo Count");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(shootButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(redarOperation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rotateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(missileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addComponent(tankPositionCheckbox))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(tankAmmoCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ammoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(tankAreaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)
                                .addComponent(tankSoldierCountLbl)
                                .addGap(18, 18, 18)
                                .addComponent(soldierSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(tankSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tankSendButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tankAreaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tankSoldierCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(soldierSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(shootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(missileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ammoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tankAmmoCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redarOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tankPositionCheckbox))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(tankSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tankSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redarOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redarOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redarOperationActionPerformed

    private void missileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_missileButtonActionPerformed

    private void tankPositionCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankPositionCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tankPositionCheckboxActionPerformed

    private void rotateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotateButtonActionPerformed

    private void tankSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankSendButtonActionPerformed
        String msg = "Tank : "+ jTextField1.getText();
        MainController.setDefenceMsg(msg);
    }//GEN-LAST:event_tankSendButtonActionPerformed


 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tank().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ammoSpinner;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton missileButton;
    private javax.swing.JButton redarOperation;
    private javax.swing.JButton rotateButton;
    private javax.swing.JButton shootButton;
    private javax.swing.JSpinner soldierSpinner;
    private javax.swing.JLabel tankAmmoCountLbl;
    private javax.swing.JLabel tankAreaTextArea;
    private javax.swing.JCheckBox tankPositionCheckbox;
    private javax.swing.JButton tankSendButton;
    private javax.swing.JSlider tankSlider;
    private javax.swing.JLabel tankSoldierCountLbl;
    private javax.swing.JTextArea tankTextArea;
    // End of variables declaration//GEN-END:variables
      
    @Override
    public void getMsgMain(String msg) {
        try{
            javax.swing.text.Document doc = tankTextArea.getDocument();
            doc.insertString(doc.getLength(), "Maincontroller: "+ msg + "\n", null);
            tankTextArea.setCaretPosition(doc.getLength());
            
        }catch(javax.swing.text.BadLocationException e){
        
    }
    }
 @Override
    public void update(int position) {
        this.position=position;
        updateButtons();
    }

    @Override
    public void areaClearlabel(boolean clearStatus) {
        if (clearStatus){
            tankAreaTextArea.setText("Area Cleared");
        }else {
            tankAreaTextArea.setText("Area is Not Clear");
        }
    }

    @Override
    public void updateButtons() {
        
        if(tankPositionCheckbox.isSelected()){
            
            if(position>80){
                 shootButton.setEnabled(true);
                 missileButton.setEnabled(true);
                 redarOperation.setEnabled(true);
                 rotateButton.setEnabled(true);
            }else if(position>60){
                shootButton.setEnabled(true);
                missileButton.setEnabled(true);
                redarOperation.setEnabled(true);
                rotateButton.setEnabled(false);
            }else if(position>40){
                shootButton.setEnabled(true);
                missileButton.setEnabled(true);
                redarOperation.setEnabled(false);
                rotateButton.setEnabled(false);
            }else if(position>20){
                shootButton.setEnabled(true);
                missileButton.setEnabled(false);
                redarOperation.setEnabled(false);
                rotateButton.setEnabled(false);
            }else{
                
                 shootButton.setEnabled(false);
                missileButton.setEnabled(false);
                redarOperation.setEnabled(false);
                rotateButton.setEnabled(false);
            }
            
            
        }
        
        }
    }

  

    
